### ISSUE TITLE
Nothing Happning

### ISSUE THREAD

**Issue by thakurrajputpankaj** [Elringus/SpriteGlow#28]

**Comment by elringus** [comment]
Hi there! Can you please provide a brief description on what you've expected to see and what you've actually get? It would be great if you could also share a screenshot, OS and Unity version you're using. Thanks!

**Comment by arhcy** [comment]
Same problem. Unity 2018.2.09b. Just nothing happens

**Comment by elringus** [comment]
@arhcy Thanks for letting us know! Can you please check whether any errors appear in the console when you add a `SpriteGlowEffect` component? Also, check out `SpriteOutline` shader asset status (it will show any compilation errors in the inspector when selected).

**Comment by elringus** [comment]
I've updated the project to work with Unity 2018.2. Feel free to reply here in case the issues will still persist.
